import './sass/main.scss';
import './js/preloader';
import { generateContentGallery } from './js/markup-list';
import { createGallaryHome } from './js/create-gallary';
import { createWachedMoviesList } from './js/create-library-wathced-list';
import { createQueueMoviesList } from './js/create-library-queue-list';
import { handleAddWatchedMovies } from './js/add-watchet-movies';
import { handleAddQueueMovies } from './js/add-queue-movies';
// import { toggleModal } from './js/modal';
// import { PAGE_SIZE, currentPage } from './js/fetch-film';
